if(NOT TARGET zlib-1.2.11)
  set(LIBNAME zlib-1.2.11)
  set(${LIBNAME}_DIR ${CMAKE_CURRENT_LIST_DIR}/../thirdparty/${LIBNAME})
  message("${LIBNAME}_DIR:${${LIBNAME}_DIR}")
  if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    add_compile_definitions(DYZ)
  endif()
  add_subdirectory(${${LIBNAME}_DIR}/)
endif()

include_directories(${${LIBNAME}_DIR}/include ${${LIBNAME}_DIR}/ ${CMAKE_BINARY_DIR}/thirdparty/${LIBNAME}  ${CMAKE_BINARY_DIR}/thirdparty/${LIBNAME}/include)

set(ZLIB_LIBRARY $<TARGET_OBJECTS:zlib>)
set(ZLIB_LIBRARIES $<TARGET_OBJECTS:zlib>)
#set(ZLIB_LIBRARY zlib)
#set(ZLIB_LIBRARIES zlib)
