if(NOT TARGET openssl-master)
  set(LIBNAME openssl-master)
  set(${LIBNAME}_DIR ${CMAKE_CURRENT_LIST_DIR}/../thirdparty/${LIBNAME})
  message("${LIBNAME}_DIR:${${LIBNAME}_DIR}")
  if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    add_compile_definitions(DYZ)
  endif()
  add_subdirectory(${${LIBNAME}_DIR}/)
endif()

include_directories(${${LIBNAME}_DIR}/include ${${LIBNAME}_DIR}/ ${CMAKE_BINARY_DIR}/thirdparty/${LIBNAME}  ${CMAKE_BINARY_DIR}/thirdparty/${LIBNAME}/include)

set(SSL_LIBRARY $<TARGET_OBJECTS:ssl>)
set(SSL_LIBRARIES $<TARGET_OBJECTS:ssl> $<TARGET_OBJECTS:crypto>)
#set(SSL_LIBRARY libssl)
#set(SSL_LIBRARIES libcrypto)
